/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Models/campfire.glb')
  return (
    <group position={[0,-2.5,0]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.campfire.geometry} material={nodes.campfire.material}>
        <group position={[0, 0.49, 0.03]} scale={[0.57, 0.49, 0.57]}>
          <mesh geometry={nodes.Mesh_bucket.geometry} material={materials.metal} />
          <mesh geometry={nodes.Mesh_bucket_1.geometry} material={materials._defaultMat} />
        </group>
        <mesh geometry={nodes.rocks.geometry} material={materials.rock} scale={[0.74, 0.7, 0.74]} />
        <mesh geometry={nodes.wood.geometry} material={nodes.wood.material} position={[-0.01, 0, -0.04]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/campfire.glb')
