/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GrassLarge({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Models/grassLarge.glb')
  return (
    <group position={[0,-2.5,0]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.grassLarge.geometry} material={materials.foliage} />
    </group>
  )
}
