/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Axe({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Models/toolAxe.glb')
  return (
    <group position={[0,-2.5,0]} ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_toolAxe.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_toolAxe_1.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_toolAxe_2.geometry} material={materials.rock} />
    </group>
  )
}
